### ISSUE TITLE
Exceptions in Spring native app are not being returned to lambda as response instead the lambda is timing out.

### ISSUE THREAD

**Issue by atyamlalithya** [spring-projects-experimental/spring-native#1568]
Hi,

I am using Spring cloud function version 3.2.1 and Spring native 0.11.1 to build a native image using GRAALVM. I am deploying the native zip in AWS lambda function with 'Custom runtime on Amazon Linux 2' as Runtime.

My function has to throw an ResponseStatusException in case of bad requests and i defaulted it in the sample for the sake of simplicity.

@Component
public class AddFunction implements Function<String, String> {

  @Override
  public String apply(String user){
    if (true) {
     throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "errorResponse");
    }
    return "Added user";
  }

 When I run this as a spring boot application / upload the jar with java11 runtime in lambda , I am getting 400 bad request response as expected. Whereas when I build a native linux image and run it through bootstrap in lambda, I can see that ResponseStatusException is printed in stack trace(logs) but the lambda is continuing to run and timing out. I want the native application to return the 400 bad request as a response to lambda like the regular jar.

Attaching the sample project to reproduce the issue, zip file I used as source in lambda and also screenshots of
[demo.zip](https://github.com/spring-projects-experimental/spring-native/files/8400462/demo.zip)
 the logs
![lambdaLog](https://user-images.githubusercontent.com/99050095/161329732-4b381e4a-dde7-42cd-b3ed-14fa8d260079.png)
![LambdaTimeOutError](https://user-images.githubusercontent.com/99050095/161329735-25832619-beaa-420c-ab5a-3d841de90519.png)
[demo-zip.zip](https://github.com/spring-projects-experimental/spring-native/files/8400458/demo-zip.zip)

**Comment by sdeleuze** [comment]
@olegz Could you please have a look to check if something should be done on our side?

**Comment by atyamlalithya** [comment]
Thanks @sdeleuze
@olegz Please let me know if you need any additional information in reproducing this.

**Comment by sj34sh** [comment]
@sdeleuze @olegz 
We are facing the same issue. Please let us know what you're able to find

**Comment by atyamlalithya** [comment]
Similar issue is handled earlier by Spring cloud function.
https://github.com/spring-cloud/spring-cloud-function/issues/716
And the solution was to throw an exception if your response is not of the type API gateway. We are doing the same but when we add Spring AOT on top and convert it to Native image ,it goes into a loop and timeout instead of returning the exception

**Comment by olegz** [comment]
Can you please upgrade to s-c-function 3.2.3? I believe the problem has been addressed

**Comment by atyamlalithya** [comment]
Hi Olegz,

Thanks for looking into this, but sadly 3.2.3 did not solve the issue. Please be noted that the java version is always working as expected. It is only the native image run through bootstrap in lambda causing this issue.

**Comment by olegz** [comment]
Ok, thank you for the confirmation and demo. I will look at it in few days

**Comment by olegz** [comment]
@atyamlalithya , your ZIP file must corrupted as there is no valid project in it

**Comment by olegz** [comment]
Regardless, I see the issue. Actually it doesn't appear to have anything to do with native, rather general custom runtime issue - https://github.com/spring-cloud/spring-cloud-function/issues/841 
Will let you know when addressed

**Comment by olegz** [comment]
Closing it as the underlying issue has been fixed and will be available in 3.2.4 of s-c-function. 
We may release it actually next week
